### ISSUE TITLE
Example using libopt3001

### ISSUE THREAD

**Issue by nak1090** [MyOctopus/libopt3001#1]
Can you give example using libopt3001 in main python ?

Regards.

**Comment by wrobell** [comment]
Please try

```
import opt3001

sensor = opt3001.Sensor(X, 0xYZ)
print(sensor.read())
```

where `X` is path to I2C device (i.e. `dev/i2c-0`) and `0xYZ` is sensor address on the I2C bus.

**Comment by exelban** [comment]
@wrobell receive next error: 
`Traceback (most recent call last):
  File "t.py", line 3, in <module>
    sensor = opt3001.Sensor(1, 0x45)
  File "/usr/local/lib/python3.4/dist-packages/opt3001-0.0.1-py3.4.egg/opt3001/glue.py", line 33, in __init__
  File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libopt3001.so.0: cannot open shared object file: No such file or directory`

And with python2.7:
`Traceback (most recent call last):
  File "t.py", line 3, in <module>
    sensor = opt3001.Sensor(1, 0x45)
  File "build/bdist.linux-armv7l/egg/opt3001/glue.py", line 33, in __init__
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libopt3001.so.0: cannot open shared object file: No such file or directory`
